StFrancisChurch/Controllers/SocietyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessObject.DataModel;
using DataAccessObject.IRepository;
using StFrancisChurch.Models;
using StFrancisChurch.Models.Utility;
using StFrancisChurch.Utility;

namespace StFrancisChurch.Controllers
{
    public class SocietyController : Controller
    {
        public ISocietyRepository _societyRepository;

        public SocietyController(ISocietyRepository societyRepository)
        {
            _societyRepository = societyRepository;
        }

        // GET: Society
        [HttpGet]
        public ActionResult Index()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        [HttpGet]
        public ActionResult Position()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        [HttpPost]
        public ActionResult Position(PositionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                var position = new Position
                {
                    PositionName = model.Name,
                    PositionDescription = model.Description
                };
                if (_societyRepository.AddPosition(position))
                {
                    var returnData = new ReturnData
                    {
                        HasValue = true,
                        Message = "Position was successfully created"
                    };
                    TempData["returnMessage"] = returnData;
                    return Redirect("Position");
                }
                ModelState.AddModelError(string.Empty, "There was an error completing the request, Please try again");
                return View(model);
            }
            catch (Exception e)
            {
                //error occured
                ModelState.AddModelError(string.Empty, "There was an error completing the request, Please try again later");
                ErrorUtil.LogError(e);
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult GetPosition(DatatableParam param)
        {
            var members = _societyRepository.GetPositions();
            var allItems = new List<PositionTableModel>();
            //Apply Searching 
            if (!string.IsNullOrEmpty(param.search.value))
            {
                var searchTerm = param.search.value;
                members = members.Where(m => m.PositionName.Contains(searchTerm) || m.PositionDescription.Contains(searchTerm));
            }

            var totalcount = members.Count();
            members = members.OrderBy(m => m.PositionName);

            //Apply Sorting/Ordering
            //IEnumerable<UserTableModel> entryTables = allItems;
            var orderColumnIndex = Convert.ToInt32(param.order[0].column);
            var orderDir = param.order[0].dir;
            if (orderDir.Equals("asc"))
            {
                if (orderColumnIndex == 1)
                {
                    members = members.OrderBy(m => m.PositionName);
                }
                if (orderColumnIndex == 2)
                {
                    members = members.OrderBy(m => m.PositionDescription);
                }
            }
            else
            {
                if (orderColumnIndex == 1)
                {
                    members = members.OrderByDescending(m => m.PositionName);
                }
                if (orderColumnIndex == 2)
                {
                    members = members.OrderByDescending(m => m.PositionDescription);
                }
            }

            //Apply Pagination
            //int.TryParse(param., out start);
            members = members.Skip(param.start).Take(param.length);

            var count = 0;

            foreach (var e in members)
            {
                count++;
                allItems.Add(new PositionTableModel
                {
                    Serial = count,
                    PositionName = e.PositionName,
                    PositionDescription = e.PositionDescription
                });
            }

            return Json(new
            {
                param.draw,
                recordsFiltered = totalcount,
                recordsTotal = totalcount,
                data = allItems,
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

StFrancisChurch/Views/Society/Index.cshtml
@using StFrancisChurch.Models.Utility
@{
    ViewBag.Title = "Station Page";
    var returns = (ReturnData)ViewBag.returns;
}

<div class="row">
    <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Stations
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="stationTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Contact</th>
                            <td>Location</td>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Contact</th>
                            <td>Location</td>
                        </tr>
                        </tfoot>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Create New Station
                <div>
                    @if (returns.HasValue)
                    {
                        <b class="text-info">@returns.Message</b>
                    }
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Index", "Station", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
                {
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Name">Name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Name" id="Name" placeholder="Enter name of station" required />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="DisplayName">Display Name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="DisplayName" id="DisplayName" placeholder="Enter display name of station" required/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="CreateDate">Created At</label>
                        <div class="col-md-8">
                            <input type="date" class="form-control" name="CreateDate" id="CreateDate" placeholder="Enter create date of station" required/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Location">Location</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Location" id="Location" placeholder="Enter location of station" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Contact">Contact</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Contact" id="Contact" placeholder="Enter contact phone of station" required/>
                        </div>
                    </div>
                    <div>
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section scripts{

    <script>
        $(document).ready(function () {
            $('#stationTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    url: "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))/Station/GetStations/",
                    type: "POST",
                    dataSrc: "data"
                },
                "columns": [
                    { "data": "Serial" },
                    { "data": "Name" },
                    { "data": "Contact" },
                    { "data": "Location" }
                ]
            });
        });
    </script>
}

StFrancisChurch/Views/Society/Position.cshtml
@using StFrancisChurch.Models.Utility
@{
    ViewBag.Title = "Position Page";
    var returns = (ReturnData)ViewBag.returns;
}

<div class="row">
    <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Positions
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="PositionTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <td>Action</td>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <td>Action</td>
                        </tr>
                        </tfoot>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Create New Position
                <div>
                    @if (returns.HasValue)
                    {
                        <b class="text-info">@returns.Message</b>
                    }
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Position", "Society", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
                {
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Name">Name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Name" id="Name" placeholder="Enter name of Position" required />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Description">Position Description</label>
                        <div class="col-md-8">
                            <textarea class="form-control" name="Description" id="Description" placeholder="Enter description of Position"></textarea>
                        </div>
                    </div>
                    <div>
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section scripts{

    <script>
        $(document).ready(function () {
            $('#PositionTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    url: "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))/Society/GetPosition/",
                    type: "POST",
                    dataSrc: "data"
                },
                "columns": [
                    { "data": "Serial" },
                    { "data": "PositionName" },
                    { "data": "PositionDescription" },
                    {
                        "data": "Action",
                        "render": function (data, type, full, meta) {
                            return '<a class="btn btn-primary" title="View this Position"><i class="fas fa-fw fa-eye"></i></a>&nbsp;' +
                                '<a class="btn btn-primary" title="Edit this Position"><i class="fas fa-fw fa-edit"></i></a>';
                        }
                    }
                ]
            });
        });
    </script>
}