StFrancisChurch/Models/BaptismViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StFrancisChurch.Models
{

    public class BaptismViewModel
    {
        [Required]
        [Display(Name = "Baptism Number")]
        public string BaptismNumber { get; set; }

        [Required]
        [Display(Name = "Baptism Place")]
        public string BaptismPlace { get; set; }

        [Required]
        [Display(Name = "Baptism Date")]
        public string BaptismDate { get; set; }

        [Required]
        [Display(Name = "Baptismal Name")]
        public string BaptismName { get; set; }
        
        [Display(Name = "Othername")]
        public string Othername { get; set; }
        
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Display(Name = "Date of Birth")]
        public string DateOfBirth { get; set; }
        
        [Display(Name = "Place of Birth")]
        public string PlaceOfBirth { get; set; }
        
        [Display(Name = "Home town")]
        public string HomeTown { get; set; }
        
        [Display(Name = "Father's name")]
        public string FathersName { get; set; }
        
        [Display(Name = "Mother's name")]
        public string MothersName { get; set; }
        
        [Display(Name = "Baptism Type")]
        public int BaptismType { get; set; }
        
        [Required]
        [Display(Name = "God parent name")]
        public string NameOfGodParent1 { get; set; }
        
        [Display(Name = "God parent name")]
        public string NameOfGodParent2 { get; set; }

        [Display(Name = "Minister's name")]
        public string NameOfMinister { get; set; }

        [Display(Name = "Remarks")]
        public string Remarks { get; set; }
        
        public int MemberId { get; set; }

        public int StationId { get; set; }

        public int Id { get; set; }
        public DateTime CreateDate { get; set; }
    }

    public class MatrimonyViewModel
    {
        [Required]
        [Display(Name = "Date Of Marraige")]
        public string DateOfMarriage { get; set; }

        [Required]
        [Display(Name = "Place Of Marraige")]
        public string PlaceOfMarriage { get; set; }

        [Required]
        [Display(Name = "Bride Fullname")]
        public string BrideFullName { get; set; }

        [Required]
        [Display(Name = "Groom Fullname")]
        public string GroomFullName { get; set; }
        
        public string BrideAddress { get; set; }

        public string GroomAddress { get; set; }

        public int BrideAge { get; set; }

        public int GroomAge { get; set; }

        public string BrideBaptismPlace { get; set; }

        public string BrideBaptismDate { get; set; }

        [Required]
        [Display(Name = "Bride Baptism number")]
        public string BrideBaptismNo { get; set; }

        public string GroomBaptismPlace { get; set; }

        public string GroomBaptismDate { get; set; }

        [Required]
        [Display(Name = "Groom Baptism number")]
        public string GroomBaptismNo { get; set; }

        [Required]
        [Display(Name = "Assisting Priest")]
        public string AssistingPriest { get; set; }

        public string BannDetails { get; set; }

        public string BrideParentName { get; set; }
        public string BrideParentHomeTown { get; set; }
        public string GroomParentName { get; set; }
        public string GroomParentHomeTown { get; set; }

        [Required]
        [Display(Name = "Witness Name")]
        public string Witness1 { get; set; }
        public string Witness2 { get; set; }
        public string Remark { get; set; }
        public int Id { get; set; }
        public DateTime CreateDate { get; set; }
    }

    public class CommunionViewModel
    {
        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }

        [Required]
        [Display(Name = "Date")]
        public string Date { get; set; }

        [Required]
        [Display(Name = "Place")]
        public string Place { get; set; }

        [Required]
        [Display(Name = "Name of Minister")]
        public string Minister { get; set; }

        [Required]
        [Display(Name = "Baptism Number")]
        public string BaptismNumber { get; set; }

        [Required]
        [Display(Name = "Baptism place")]
        public string BaptismPlace { get; set; }

        [Required]
        [Display(Name = "Baptism date")]
        public string BaptismDate { get; set; }
        public int Id { get; set; }
        public DateTime CreateDate { get; set; }
    }

    public class ConfirmationViewModel
    {
        [Required]
        [Display(Name = "Number")]
        public string Number { get; set; }
        public string ConfirmationName { get; set; }
        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string Date { get; set; }
        public string Place { get; set; }
        public string Minister { get; set; }
        public string Sponsor { get; set; } 

        [Required]
        [Display(Name = "Baptism Number")]
        public string BaptismNumber { get; set; }
        public string BaptismPlace { get; set; }
        public string BaptismDate { get; set; }
        public int Id { get; set; }
        public DateTime CreateDate { get; set; }
    }

    public class PositionViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

StFrancisChurch/Controllers/SacramentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessObject.DataModel;
using DataAccessObject.IRepository;
using StFrancisChurch.Models;
using StFrancisChurch.Models.Utility;
using StFrancisChurch.Utility;

namespace StFrancisChurch.Controllers
{
    [Authorize]
    public class SacramentController : Controller
    {
        private ISacramentRepository _sacramentRepository;

        public SacramentController(ISacramentRepository sacramentRepository)
        {
            _sacramentRepository = sacramentRepository;
        }

        // GET: Sacrament
        public ActionResult Index()
        {
            ViewBag.SacramentCounts = ViewUtility.GetSacramentsCount();
            return View();
        }

        public ActionResult Communion()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        public ActionResult Confirmation()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        public ActionResult Baptism()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        public ActionResult Matrimony()
        {
            var returnData = (ReturnData)TempData["returnMessage"] ?? new ReturnData
            {
                HasValue = false
            };
            ViewBag.returns = returnData;
            return View();
        }

        [HttpGet]
        public ActionResult CreateBaptism()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateBaptism(BaptismViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                var baptism = new Baptism
                {
                    BapitsmNumber = model.BaptismNumber,
                    BaptismPlace = model.BaptismPlace,
                    BaptismDate = DateTime.Parse(model.BaptismDate),
                    BaptismName = model.BaptismName,
                    BaptismType = model.BaptismType,
                    Othername = model.Othername,
                    Surname = model.Surname,
                    DateOfBirth = DateTime.Parse(model.DateOfBirth),
                    PlaceOfBirth = model.PlaceOfBirth,
                    HomeTown = model.HomeTown,
                    FathersName = model.FathersName,
                    MothersName = model.MothersName,
                    NameOfGodParent1 = model.NameOfGodParent1,
                    NameOfGodParent2 = model.NameOfGodParent2,
                    NameOfMinister = model.NameOfMinister,
                    Remarks = model.Remarks,
                    Deleted = 0,
                    CreateDate = DateTime.Now
                };
                if (_sacramentRepository.AddBaptism(baptism))
                {
                    var returnData = new ReturnData
                    {
                        HasValue = true,
                        Message = "Baptismal record was successfully created"
                    };
                    TempData["returnMessage"] = returnData;
                    return Redirect("Baptism");
                }
                ModelState.AddModelError(string.Empty, "There was an error completing the registration, Please check if the bapismal number is correct");
                return View(model);
            }
            catch (Exception e)
            {
                //error occured
                ModelState.AddModelError(string.Empty, "There was an error completing the registration, Please try again later");
                ErrorUtil.LogError(e);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult EditBaptism(int id)
        {
            var baptismRecord = _sacramentRepository.GetBaptism(id);
            var baptism = new BaptismViewModel
            {
                Id = baptismRecord.Id,
                BaptismNumber = baptismRecord.BapitsmNumber,
                BaptismPlace = baptismRecord.BaptismPlace,
                BaptismDate = baptismRecord.BaptismDate.ToString("yyyy-MM-dd"),
                BaptismName = baptismRecord.BaptismName,
                BaptismType = baptismRecord.BaptismType,
                Othername = baptismRecord.Othername,
                Surname = baptismRecord.Surname,
                DateOfBirth = baptismRecord.DateOfBirth?.ToString("yyyy-MM-dd"),
                PlaceOfBirth = baptismRecord.PlaceOfBirth,
                HomeTown = baptismRecord.HomeTown,
                FathersName = baptismRecord.FathersName,
                MothersName = baptismRecord.MothersName,
                NameOfGodParent1 = baptismRecord.NameOfGodParent1,
                NameOfGodParent2 = baptismRecord.NameOfGodParent2,
                NameOfMinister = baptismRecord.NameOfMinister,
                Remarks = baptismRecord.Remarks,
                CreateDate = baptismRecord.CreateDate
            };
            return View(baptism);
        }

        [HttpPost]
        public ActionResult EditBaptism(BaptismViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                var baptism = new Baptism
                {
                    Id = model.Id,
                    BapitsmNumber = model.BaptismNumber,
                    BaptismPlace = model.BaptismPlace,
                    BaptismDate = DateTime.Parse(model.BaptismDate),
                    BaptismName = model.BaptismName,
                    BaptismType = model.BaptismType,
                    Othername = model.Othername,
                    Surname = model.Surname,
                    DateOfBirth = DateTime.Parse(model.DateOfBirth),
                    PlaceOfBirth = model.PlaceOfBirth,
                    HomeTown = model.HomeTown,
                    FathersName = model.FathersName,
                    MothersName = model.MothersName,
                    NameOfGodParent1 = model.NameOfGodParent1,
                    NameOfGodParent2 = model.NameOfGodParent2,
                    NameOfMinister = model.NameOfMinister,
                    Remarks = model.Remarks,
                    Deleted = 0,
                    CreateDate = model.CreateDate,
                    UpdateDate = DateTime.Now
                };
                if (_sacramentRepository.UpdateBaptism(baptism))
                {
                    var returnData = new ReturnData
                    {
                        HasValue = true,
                        Message = "Baptismal record was successfully Updated"
                    };
                    TempData["returnMessage"] = returnData;
                    //return Redirect("/Baptism");
                    return RedirectToAction("Baptism");
                }
                ModelState.AddModelError(string.Empty, "There was an error completing the registration, Please check if the bapismal number is correct, also check the record");
                return View(model);
            }
            catch (Exception e)
            {
                //error occured
                ModelState.AddModelError(string.Empty, "There was an error completing the registration, Please try again later");
                ErrorUtil.LogError(e);
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult GetBaptisedMembers(DatatableParam param)
        {
            var members = _sacramentRepository.GetBaptisedMembers();
            var allItems = new List<BaptismTableModel>();
            //Apply Searching 
            if (!string.IsNullOrEmpty(param.search.value))
            {
                var searchTerm = param.search.value;
                members = members.Where(m => m.BaptismName.Contains(searchTerm) || m.BapitsmNumber.Contains(searchTerm) || m.Surname.Contains(searchTerm));
            }

            var totalcount = members.Count();
            members = members.OrderBy(m => m.BaptismName);

            //Apply Sorting/Ordering
            //IEnumerable<UserTableModel> entryTables = allItems;
            var orderColumnIndex = Convert.ToInt32(param.order[0].column);
            var orderDir = param.order[0].dir;
            if (orderDir.Equals("asc"))
            {
                if (orderColumnIndex == 1)
                {
                    members = members.OrderBy(m => m.BaptismName);
                }
                if (orderColumnIndex == 2)
                {
                    members = members.OrderBy(m => m.Surname);
                }
                if (orderColumnIndex == 3)
                {
                    members = members.OrderBy(m => m.Othername);
                }
            }
            else
            {
                if (orderColumnIndex == 1)
                {
                    members = members.OrderByDescending(m => m.BaptismName);
                }
                if (orderColumnIndex == 2)
                {
                    members = members.OrderByDescending(m => m.Surname);
                }
                if (orderColumnIndex == 3)
                {
                    members = members.OrderByDescending(m => m.Othername);
                }
            }

            //Apply Pagination
            //int.TryParse(param., out start);
            members = members.Skip(param.start).Take(param.length);

            var count = 0;

StFrancisChurch/Views/Sacrament/CreateBaptism.cshtml
@using StFrancisChurch.Models
@using StFrancisChurch.Utility
@model BaptismViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Baptismal Register
    </div>
    <div class="card-body">
        @using (Html.BeginForm("CreateBaptism", "Sacrament", FormMethod.Post, new { @role = "form", @enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true, "", new { @style = "color :red" })
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="BaptismNumber">Baptism Number</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="BaptismNumber" id="BaptismNumber" placeholder="Enter Baptismal number">
                            @Html.ValidationMessageFor(m => m.BaptismNumber, "", new { @style = "color:red" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="BaptismDate">Baptism Date</label>
                        <div class="col-md-8">
                            <input type="date" class="form-control" name="BaptismDate" id="BaptismDate" placeholder="Enter Baptismal date">
                            @Html.ValidationMessageFor(m => m.BaptismDate, "", new { @style = "color:red" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="BaptismPlace">Baptism Place</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="BaptismPlace" id="BaptismPlace" placeholder="Enter Baptismal place">
                            @Html.ValidationMessageFor(m => m.BaptismPlace, "", new { @style = "color:red" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="BaptismName">Baptism name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="BaptismName" id="BaptismName" placeholder="Enter baptism name">
                            @Html.ValidationMessageFor(m => m.BaptismName, "", new { @style = "color:red" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Surname">Surname</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Surname" id="Surname" placeholder="Enter surname">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Othername">Othername</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Othername" id="Othername" placeholder="Enter othername">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="DateOfBirth">Date of birth</label>
                        <div class="col-md-8">
                            <input type="date" class="form-control" name="DateOfBirth" id="DateOfBirth" placeholder="Enter date of birth">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="PlaceOfBirth">Place of birth</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="PlaceOfBirth" id="PlaceOfBirth" placeholder="Enter place of birth">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="HomeTown">Home Town</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="HomeTown" id="HomeTown" placeholder="Enter home town">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="FathersName">Father's Name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="FathersName" id="FathersName" placeholder="Enter father's name">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="MothersName">Mother's Name</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="MothersName" id="MothersName" placeholder="Enter mother's name">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="BaptismType">BaptismType</label>
                        <div class="col-md-8">
                            @Html.DropDownList("BaptismType", new SelectList(ViewUtility.GetBaptismType(), "Id", "Name", null), "Select baptism type", new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="NameOfGodParent1">Name of 1<sup>st</sup> God parent</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="NameOfGodParent1" id="NameOfGodParent1" placeholder="Enter name of 1st God parent">
                            @Html.ValidationMessageFor(m => m.NameOfGodParent1, "", new { @style = "color:red" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="NameOfGodParent2">Name of 2<sup>nd</sup> God parent</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="NameOfGodParent2" id="NameOfGodParent2" placeholder="Enter name of 2nd God parent">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="NameOfMinister">Name Of Minister</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="NameOfMinister" id="NameOfMinister" placeholder="Enter name of minister">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="control-label col-md-4 text-right" for="Remark">Remark</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="Remark" id="Remark" placeholder="Enter remark">
                        </div>
                    </div>
                </div>
                <div class="col-md-12 col-md-push-8">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary btn-modify">
                    </div>
                </div>
            </div>
        }
    </div>
    
</div>
@section scripts{

    <script>
        $(document).ready(function () {

        });
    </script>
}

StFrancisChurch/Views/Sacrament/CreateCommunion.cshtml
@using StFrancisChurch.Models
@using StFrancisChurch.Utility
@model CommunionViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Communion Register
    </div>
    <div class="card-body">
        @using (Html.BeginForm("CreateCommunion", "Sacrament", FormMethod.Post, new { @role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @style = "color :red" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="Surname">Surname</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="Surname" id="Surname" placeholder="Enter Surname">
                        @Html.ValidationMessageFor(m => m.Surname, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="Othernames">Othernames</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="Othernames" id="Othernames" placeholder="Enter Othernames">
                        @Html.ValidationMessageFor(m => m.Othernames, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="FathersName">Father's Name</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="FathersName" id="FathersName" placeholder="Enter Father's Name">
                        @Html.ValidationMessageFor(m => m.FathersName, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="MothersName">Mother's Name</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="MothersName" id="MothersName" placeholder="Enter Mother's Name">
                        @Html.ValidationMessageFor(m => m.MothersName, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="Date">Date</label>
                    <div class="col-md-8">
                        <input type="date" class="form-control" name="Date" id="Date" placeholder="Enter Communial date">
                        @Html.ValidationMessageFor(m => m.Date, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="Place">Place</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="Place" id="Place" placeholder="Enter Comunion Place">
                        @Html.ValidationMessageFor(m => m.Place, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="BaptismNumber">Baptism Number</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="BaptismNumber" id="BaptismNumber" placeholder="Enter Baptismal number">
                        @Html.ValidationMessageFor(m => m.BaptismNumber, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="BaptismPlace">Baptism Place</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="BaptismPlace" id="BaptismPlace" placeholder="Enter Baptismal place">
                        @Html.ValidationMessageFor(m => m.BaptismPlace, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="BaptismDate">Baptism Date</label>
                    <div class="col-md-8">
                        <input type="date" class="form-control" name="BaptismDate" id="BaptismDate" placeholder="Enter Baptismal date">
                        @Html.ValidationMessageFor(m => m.BaptismDate, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4 text-right" for="Minister">Minister</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="Minister" id="Minister" placeholder="Enter Minister's Name">
                        @Html.ValidationMessageFor(m => m.Minister, "", new { @style = "color:red" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-md-push-8">
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary btn-modify">
                </div>
            </div>
        </div>
        }
    </div>
    
</div>
@section scripts{

    <script>
        $(document).ready(function () {

        });
    </script>
}